favicon: null
name: House Groszko
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7158969
  brandStrength: 0.04493782040663064
  lightness: 0.5816327
  brandColors: []
  rhythmicContrast: 0.7097495
typography_spectrum: 0.1401718
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
