name: House Groszko
favicon: null
layout_spectrum: 0.8627075576223433
typography_spectrum: 0.48582229227758944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.044937820406630635
  lightness: 0.06258965493179858
  saturation: 0.6086015414912254
  rhythmicContrast: 0.7097494478803128
purpose: []
